- name: Provisioning AWS EC2 Instance
  hosts: localhost
  gather_facts: no

  vars_files:
    - ec2_vars.yml

  tasks:
    - name: Launch EC2 Instance
      amazon.aws.ec2_instance:
        instance_type: t2.micro
        exact_count: "{{ exact_count }}" # Number of instances to launch
        name: "{{ item }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        security_groups:
          - "{{ security_group }}"
        image_id: "{{ image_id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ item }}"
        user_data: "{{ lookup('file', 'tools_userdata.sh') }}"
      loop: "{{ instances }}"
      register: ec2_instances_info
    
    - name: Print only public IPs of EC2 instances
      ansible.builtin.debug:
        msg: "The IP address of {{ item.item }} server is: {{ item.instances[0].public_ip_address }}"
      loop: "{{ ec2_instances_info.results }}"
      loop_control:
        label: "{{ item.item }}"
